// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGbxoXhotKwAGBLQhpDNuaIgxcC3N73as',
    appId: '1:540067844291:web:8f0232c503570c1ace1276',
    messagingSenderId: '540067844291',
    projectId: 'cares-8757b',
    authDomain: 'cares-8757b.firebaseapp.com',
    storageBucket: 'cares-8757b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_MrL2q6tojVZjbyLJpQxvclSaZvvPiws',
    appId: '1:540067844291:android:37f928b4655d3f0ece1276',
    messagingSenderId: '540067844291',
    projectId: 'cares-8757b',
    storageBucket: 'cares-8757b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfnH7ivEKqGFCpOF0zhYOk1RraRsa-sjY',
    appId: '1:540067844291:ios:0ef90f98727182abce1276',
    messagingSenderId: '540067844291',
    projectId: 'cares-8757b',
    storageBucket: 'cares-8757b.appspot.com',
    androidClientId: '540067844291-qt6ob6udftccg943dskhja77bh5arf3v.apps.googleusercontent.com',
    iosClientId: '540067844291-f78qp16pgejrehr5jobt6klqdvf91v2p.apps.googleusercontent.com',
    iosBundleId: 'com.example.caresApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfnH7ivEKqGFCpOF0zhYOk1RraRsa-sjY',
    appId: '1:540067844291:ios:0ef90f98727182abce1276',
    messagingSenderId: '540067844291',
    projectId: 'cares-8757b',
    storageBucket: 'cares-8757b.appspot.com',
    androidClientId: '540067844291-qt6ob6udftccg943dskhja77bh5arf3v.apps.googleusercontent.com',
    iosClientId: '540067844291-f78qp16pgejrehr5jobt6klqdvf91v2p.apps.googleusercontent.com',
    iosBundleId: 'com.example.caresApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGbxoXhotKwAGBLQhpDNuaIgxcC3N73as',
    appId: '1:540067844291:web:5d02e74052c4aee6ce1276',
    messagingSenderId: '540067844291',
    projectId: 'cares-8757b',
    authDomain: 'cares-8757b.firebaseapp.com',
    storageBucket: 'cares-8757b.appspot.com',
  );
}
